#!/bin/bash
[ -z "$PYFILE" ] && echo "Error: PYFILE is not set or file does not exist" && exit 1; python3 "$PYFILE" && echo "Python script executed successfully." || echo "Error: Python script execution failed."

